/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.ActionListenerBtns;
import Controller.ActionListenerForTable;
import Controller.ActionListenerMenuItems;
import Model.InvoiceHeader;
import Model.InvoiceHeaderTable;
import Model.InvoiceLine;
import Model.InvoiceLineTable;





import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
/**
 *
 * @author Marwa Mahmoud
 */
public class SIG_Frame extends JFrame{
    
     public SIG_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Invoice = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Items = new javax.swing.JTable();
        jButton_Create = new javax.swing.JButton();
        jButton_Create.addActionListener(listenerBtns);
        jButton_Delete = new javax.swing.JButton();
        jButton_Delete.addActionListener(listenerBtns);
        jButton_Save = new javax.swing.JButton();
        jButton_Save.addActionListener(listenerBtns);
        jButton_Cancle = new javax.swing.JButton();
        jButton_Cancle.addActionListener(listenerBtns);
        jLabel_InNumber = new javax.swing.JLabel();
        jLabel_InDate = new javax.swing.JLabel();
        jLabel_CustomerName = new javax.swing.JLabel();
        jLabel_InTotal = new javax.swing.JLabel();
        jTextField_InvoiceDate = new javax.swing.JTextField();
        jTextField_CustomerName = new javax.swing.JTextField();
        jLabel_InvoiceNumber = new javax.swing.JLabel();
        jLabel_InvoiceTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuIteamLoadFile = new javax.swing.JMenuItem();
        jMenuItemSavveFile = new javax.swing.JMenuItem();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 550));

        jTable_Invoice.getSelectionModel().addListSelectionListener(selectListenerForTable);
        jScrollPane1.setViewportView(jTable_Invoice);

        jTable_Items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable_Items);

        jButton_Create.setText("Create Invoice");
        jButton_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CreateActionPerformed(evt);
            }
        });

        jButton_Delete.setText("Delete Invoice");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_Save.setText("Add Item");

        jButton_Cancle.setText("Delete Item");

        jLabel_InNumber.setText("Inv. No.        :");

        jLabel_InDate.setText("Date              :");

        jLabel_CustomerName.setText("Cust. Name   :");

        jLabel_InTotal.setText("Invoice Total :");

        jLabel1.setText("Table of Invoices");

        jLabel2.setText("INVs Items    :");

        jMenu1.setText("File");

        jMenuIteamLoadFile.setText("Load File");
        jMenuIteamLoadFile.addActionListener(listenerMenuItems);
        jMenu1.add(jMenuIteamLoadFile);

        jMenuItemSavveFile.setText("Save File");
        jMenuItemSavveFile.addActionListener(listenerMenuItems);
        jMenuItemSavveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSavveFileActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSavveFile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276)
                        .addComponent(jLabel_InNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel_InvoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_InDate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jTextField_InvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jTextField_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_InTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel_InvoiceTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton_Create)
                .addGap(105, 105, 105)
                .addComponent(jButton_Delete)
                .addGap(67, 67, 67)
                .addComponent(jButton_Save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Cancle)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_InNumber)
                            .addComponent(jLabel_InvoiceNumber))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_InDate)
                            .addComponent(jTextField_InvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CustomerName)
                            .addComponent(jTextField_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_InTotal)
                            .addComponent(jLabel_InvoiceTotal))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Create)
                    .addComponent(jButton_Delete)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Save)
                        .addComponent(jButton_Cancle)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CreateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jMenuItemSavveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSavveFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSavveFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIG_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIG_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIG_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIG_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIG_Frame().setVisible(true);
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancle;
    private javax.swing.JButton jButton_Create;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_CustomerName;
    private javax.swing.JLabel jLabel_InDate;
    private javax.swing.JLabel jLabel_InNumber;
    private javax.swing.JLabel jLabel_InTotal;
    private javax.swing.JLabel jLabel_InvoiceNumber;
    private javax.swing.JLabel jLabel_InvoiceTotal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuIteamLoadFile;
    private javax.swing.JMenuItem jMenuItemSavveFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable_Invoice;
    private javax.swing.JTable jTable_Items;
    private javax.swing.JTextField jTextField_CustomerName;
    private javax.swing.JTextField jTextField_InvoiceDate;
    // End of variables declaration//GEN-END:variables

    private ActionListenerBtns listenerBtns= new ActionListenerBtns(this);
    private ActionListenerMenuItems listenerMenuItems=new ActionListenerMenuItems(this);
    private ArrayList<InvoiceHeader> invoicesArr;
    private InvoiceHeaderTable headerTable;
    public static SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
    private ActionListenerForTable selectListenerForTable=new ActionListenerForTable(this);
    private ArrayList<InvoiceLine> linesArr;
    private InvoiceLineTable lineTable;

    public InvoiceLineTable getLineTable() {
        return lineTable;
    }

    public void setLineTable(InvoiceLineTable lineTable) {
        this.lineTable = lineTable;
    }

    public ArrayList<InvoiceLine> getLinesArr() {
        return linesArr;
    }

    public void setLinesArr(ArrayList<InvoiceLine> linesArr) {
        this.linesArr = linesArr;
    }

    public void setInvoicesArr(ArrayList<InvoiceHeader> invoicesArr) {
        this.invoicesArr = invoicesArr;
    }

    public ArrayList<InvoiceHeader> getInvoicesArr() {
        return invoicesArr;
    }

    public InvoiceHeader getInvoiceHeaderObject(int code){
        for(InvoiceHeader InvoiceHeaderObject : invoicesArr){
            if(InvoiceHeaderObject.getinvoiceNum()==code){
                return InvoiceHeaderObject;
            }
        }
        return null;  //almost non return
    }


    public InvoiceHeaderTable getHeaderTable() {
        return headerTable;
    }

    public void setHeaderTable(InvoiceHeaderTable headerTable) {
        this.headerTable = headerTable;
    }

    public JTable getjTable_Invoice() {
        return jTable_Invoice;

    }

    public JTable getjTable_Items() {
        return jTable_Items;
    }

    public JTextField getjTextField_CustomerName() {
        return jTextField_CustomerName;
    }

    public JTextField getjTextField_InvoiceDate() {
        return jTextField_InvoiceDate;
    }

    public JLabel getjLabel_InvoiceNumber() {
        return jLabel_InvoiceNumber;
    }

    public JLabel getjLabel_InvoiceTotal() {
        return jLabel_InvoiceTotal;
    }

    public ActionListenerBtns getListenerBtns() {
        return listenerBtns;
    }

 


}


